# CAMEL Model for all the cooperatives

## Functions

In [2]:
import pandas as pd

### Capital Adequacy

In [3]:
def get_value(excel_file, cuenta, company_name, date_):
    mask = (excel_file['CUENTA'] == cuenta) & (excel_file['fecha'] == date_)
    series = excel_file.loc[mask, company_name]
    if series.empty or series.isna().all():
        return None
    return series.iloc[-1]  # último corte del mes, no el primero

# Loss of Assets
def loss_of_assets(excel_file, company_name, year, month):
    date_ = pd.Timestamp(f'{int(year)}-{int(month)}-01')
    v1 = get_value(excel_file, 300000, company_name, date_)
    v2 = get_value(excel_file, 310000, company_name, date_)
    if v1 is None or v2 is None or v2 == 0:
        return None
    return v1 / v2

# Solvency Ratio
def solvency_ratio():
    return 0

# Indicator of the relationship between the non-reducible minimum social contributions and the Share Capital
def min_social_contrib_social_capital(excel_file, company_name, year, month):
    date_ = pd.Timestamp(f'{int(year)}-{int(month)}-01')
    
    mask1 = (excel_file['CUENTA'] == 311000) & (excel_file['fecha'] == date_)
    mask2 = (excel_file['CUENTA'] == 310000) & (excel_file['fecha'] == date_)
    
    account_coop1 = excel_file.loc[mask1, company_name]
    account_coop2 = excel_file.loc[mask2, company_name]

    if account_coop1.empty or account_coop2.empty:
        return 0
    
    value1 = list(account_coop1)[0]
    value2 = list(account_coop2)[0]
    
    return value1 / value2 if value2 != 0 else 0


# --- Sum the values of every row 'i' in a specific company
def summation(excel_file, index_list, company_name, year, month):
    suma = 0
    date_ = pd.Timestamp(f'{int(year)}-{int(month)}-01')
    for i in index_list:
        mask = (excel_file['CUENTA'] == i) & (excel_file['fecha'] == date_)
        account_coop = excel_file.loc[mask, company_name]
        if account_coop.empty or account_coop.isna().all():
            value = 0
        else:
            value = account_coop.iloc[0]  # o .sum() si esperas múltiples filas
        suma += value
    return suma


# Indicator of the relationship between Institutional Capital and Total Assets
def capital_contribution_ratio(excel_file, company_name, year, month):
    date_ = pd.Timestamp(f'{int(year)}-{int(month)}-01')
    capital_inst_indices = [320000, 330000, 340000]
    capital_inst = summation(excel_file, capital_inst_indices, company_name, year, month)
    
    mask_total_assets = (excel_file['CUENTA'] == 100000) & (excel_file['fecha'] == date_)
    total_assets = excel_file.loc[mask_total_assets, company_name]
    if total_assets.empty:
        return 0
    total_assets_ = list(total_assets)
    value1 = capital_inst
    value2 = total_assets_[0]

    return value1 / value2 if value2 != 0 else 0

### Assets Quality

In [4]:
# Functions for quality indicator by risk with penalties
def gross_portfolio(excel_file, company_name, year, month):
    gross_portfolio_indices = [
        140400, 140500, 141100, 141200, 144100, 144200,
        144800, 145400, 145500, 146100, 146200, 146900
    ]
    return summation(excel_file, gross_portfolio_indices, company_name, year, month)

def risk_quality_indicator(excel_file, company_name, year, month):
    risk_portfolio_indices = [
        140410, 140415, 140420, 140425, 140510, 140515, 140520, 140525,
        141110, 141115, 141120, 141125, 141210, 141215, 141220, 141225,
        144110, 144115, 144120, 144125, 144210, 144215, 144220, 144225,
        144810, 144815, 144820, 144825, 145410, 145415, 145420, 145425,
        145510, 145515, 145520, 145525, 146110, 146115, 146120, 146125,
        146210, 146215, 146220, 146225, 146910, 146915, 146920, 146925,
        146935, 146940, 146945, 146950
    ]
    qualified_portfolio = summation(excel_file, risk_portfolio_indices, company_name, year, month)
    gross_portf = gross_portfolio(excel_file,company_name, year, month)

    return qualified_portfolio / gross_portf if gross_portf != 0 else 0

def risk_quality_with_writeoffs(excel_file, company_name, year, month):
    # total qualified portfolio
    qualified_portfolio = risk_quality_indicator(excel_file, company_name, year, month)
    # writeoffs
    mask = (excel_file['CUENTA'] == 831015) & (excel_file['fecha'] == f'{int(year)}-{int(month)}-01')
    writeoffs_list = list(excel_file.loc[mask, company_name])
    writeoffs = writeoffs_list[0] if writeoffs_list else 0
    total_with_writeoffs_indices = [
        140400, 140500, 141100, 141200, 144100, 144200, 144800,
        145400, 145500, 146100, 146200, 146900, 831015
    ]
    total_with_writeoffs = summation(excel_file, total_with_writeoffs_indices, company_name, year, month)

    return (qualified_portfolio + writeoffs) / total_with_writeoffs if total_with_writeoffs != 0 else 0

# Total Portfolio at Risk Coverage Indicator
def total_risk_coverage_indicator(excel_file, company_name, year, month):
    deterioration_indices = [140800, 144500, 145100, 145800, 146500, 146800, 147100]
    provisions = summation(excel_file, deterioration_indices, company_name, year, month)
    gross_portf = gross_portfolio(excel_file, company_name, year, month)
    return provisions / gross_portf if gross_portf != 0 else 0

# Productive asset
def productive_assets_ratio(excel_file, company_name, year, month):
    productive_assets_indices = [
        112000, 120000, 130000, 140405, 140410, 140505, 140510,
        141105, 141110, 141205, 141210, 144105, 144110, 144205,
        144210, 144805, 144810, 145405, 145410, 145505, 145510,
        146105, 146110, 146205, 146210, 146905, 146910, 146930,
        146935, 160505, 161505
    ]
    productive_assets = summation(excel_file, productive_assets_indices, company_name, year, month)
    mask = (excel_file['CUENTA'] == 100000) & (excel_file['fecha'] == f'{int(year)}-{int(month)}-01')
    total_assets_list = list(excel_file.loc[mask, company_name])
    total_assets = total_assets_list[0] if total_assets_list else 0
    return productive_assets / total_assets if total_assets != 0 else 0

# Individual Coverage Indicator of the Unproductive Portfolio for the At-Risk Portfolio
def individual_coverage_nonproductive_portfolio(excel_file, company_name, year, month):
    provisions_cde_indices = [
        140815, 140820, 140825,
        144525, 144530, 144535, 144540, 144545, 144550,
        145115, 145120, 145125,
        145825, 145830, 145835, 145840, 145845, 145850,
        146525, 146530, 146535, 146540, 146545, 146550,
        147115, 147120, 147125, 147140, 147145, 147150
    ]
    provisions = summation(excel_file, provisions_cde_indices, company_name, year, month)

    overdue_portfolio_indices = [
        140415, 140420, 140425, 140515, 140520, 140525,
        141115, 141120, 141125, 141215, 141220, 141225,
        144115, 144120, 144125, 144215, 144220, 144225,
        144815, 144820, 144825, 145415, 145420, 145425,
        145515, 145520, 145525, 146115, 146120, 146125,
        146215, 146220, 146225, 146915, 146920, 146925,
        146940, 146945, 146950
    ]
    overdue = summation(excel_file, overdue_portfolio_indices, company_name, year, month)

    return provisions / overdue if overdue != 0 else 0

### Managerial Quality

In [5]:
# Operating Financial Margin Indicator
def financial_margin_operation(excel_file, company_name, year, month):
    date_filter = f'{int(year)}-{int(month)}-01'

    pos_list = list(excel_file.loc[(excel_file['CUENTA'] == 410000) & (excel_file['fecha'] == date_filter), company_name])
    positive_margin = pos_list[0] if pos_list else 0

    neg_list1 = list(excel_file.loc[(excel_file['CUENTA'] == 610000) & (excel_file['fecha'] == date_filter), company_name])
    negative_margin1 = neg_list1[0] if neg_list1 else 0

    serie = excel_file.loc[(excel_file['CUENTA'] == 700000) & (excel_file['fecha'] == date_filter), company_name]
    negative_margin2 = 0 if serie.empty else serie.iloc[0]

    sales_list = list(excel_file.loc[(excel_file['CUENTA'] == 410000) & (excel_file['fecha'] == date_filter), company_name])
    sales_income = sales_list[0] if sales_list else 0

    negative_margin = negative_margin1 + negative_margin2
    return (positive_margin - negative_margin) / sales_income if sales_income != 0 else 0


# Operating Margin Indicator (usa 'summation', no se modifica)
def operational_margin(excel_file, company_name, year, month):
    income_pos_indices = [410000, 422500]
    income_neg_indices = [610000, 700000, 510500, 510700, 511000, 511500, 540000]
    sales_indices = [410000, 422500]
    income_pos = summation(excel_file, income_pos_indices, company_name, year, month)
    income_neg = summation(excel_file, income_neg_indices, company_name, year, month)
    sales_income = summation(excel_file, sales_indices, company_name, year, month)
    return (income_pos - income_neg) / sales_income if sales_income != 0 else 0

# Indicator of the relationship between financial obligations and total liabilities
def financial_obligations_ratio(excel_file, company_name, year, month):
    date_filter = f'{int(year)}-{int(month)}-01'

    obligations_list = list(excel_file.loc[(excel_file['CUENTA'] == 230000) & (excel_file['fecha'] == date_filter), company_name])
    obligations = obligations_list[0] if obligations_list else 0

    total_liabilities_list = list(excel_file.loc[(excel_file['CUENTA'] == 200000) & (excel_file['fecha'] == date_filter), company_name])
    total_liabilities = total_liabilities_list[0] if total_liabilities_list else 0

    return obligations / total_liabilities if total_liabilities != 0 else 0

# Balance structure (usa 'summation', no se modifica)
def balance_structure(excel_file, company_name, year, month):
    productive_assets_indices = [
        112000, 120000, 130000, 140405, 140410, 140505, 140510,
        141105, 141110, 141205, 141210, 144105, 144110, 144205,
        144210, 144805, 144810, 145405, 145410, 145505, 145510,
        146105, 146110, 146205, 146210, 146905, 146910, 146930,
        146935, 160505, 161505
    ]
    interest_liabilities_indices = [210000, 230000]
    productive_assets = summation(excel_file, productive_assets_indices, company_name, year, month)
    interest_liabilities = summation(excel_file, interest_liabilities_indices, company_name, year, month)
    return productive_assets / interest_liabilities if interest_liabilities != 0 else 0

### Earnings Strength

In [6]:
# Return on equity indicator
def ROE(excel_file, company_name, year, month, n=1):
    fecha_actual = pd.Period(f"{year}-{month:02d}", freq="M")
    fecha_str = str(fecha_actual.to_timestamp().date())
    meses_previos = [str((fecha_actual - i).to_timestamp().date()) for i in range(1, 13)]

    num_values = excel_file.loc[
        (excel_file["CUENTA"] == 530000) & (excel_file["fecha"] == fecha_str),
        company_name
    ].values
    num = num_values[0] if len(num_values) > 0 else 0

    valores = excel_file.loc[
        (excel_file["CUENTA"] == 300000) & (excel_file["fecha"].isin(meses_previos)),
        company_name
    ].values

    if len(valores) == 0 or n == 0 or num == 0:
        return None

    prom_300000 = valores.mean()
    roe = (1 + ((num / prom_300000) / n))**12 - 1
    return roe


# Net margin indicator
def net_margin_indicator(excel_file, company_name, year, month):
    net_surplus_list = list(excel_file.loc[(excel_file['CUENTA'] == 530000) & (excel_file['fecha'] == f'{int(year)}-{int(month)}-01'), company_name])
    net_surplus = net_surplus_list[0] if net_surplus_list else 0
    incomes_indices = [410000, 422500]
    total_incomes = summation(excel_file, incomes_indices, company_name, year, month)
    return net_surplus / total_incomes if total_incomes != 0 else 0

# Indicator of return on invested capital
def ROIC(excel_file, company_name, year, month, n=1):
    fecha_actual = pd.Period(f"{year}-{month:02d}", freq="M")
    meses_previos = [str((fecha_actual - i).to_timestamp().date()) for i in range(1, 13)]

    # Numerator
    num_values = excel_file.loc[
        (excel_file["CUENTA"] == 530000) & (excel_file["fecha"] == str(fecha_actual.to_timestamp().date())),
        company_name
    ].values
    num = num_values[0] if len(num_values) > 0 else 0

    # Denominator
    cuentas = [210000, 230000, 300000]
    promedios = []
    for cuenta in cuentas:
        valores = excel_file.loc[
            (excel_file["CUENTA"] == cuenta) & (excel_file["fecha"].isin(meses_previos)),
            company_name
        ].values
        prom = valores.mean() if len(valores) > 0 else 0
        promedios.append(prom)

    denom = sum(promedios)

    if denom == 0 or n == 0 or num == 0:
        return None  # division by zero or no data

    roic = (1 + ((num / denom) / n))**12 - 1
    return roic

### Liquidicy Efficiency

In [7]:
# Liquidity Risk Indicator
def liquidity_risk():
    return 0

## Read the csv for all the cooperatives

In [8]:
coops = pd.read_csv("../tablas/Datos_2021_2025_cooperativas.csv")
coops['fecha'] = pd.to_datetime(coops['fecha'])
coops

,CUENTA,NOMBRE CUENTA,COOPERATIVA DE EMPLEADOS DE CAFAM,COOPERATIVA DE LOS PROFESIONALES DE LA SALUD COASMEDAS,COOPERATIVA PARA EL BIENESTAR SOCIAL,COOPERATIVA FINANCIERA SAN FRANCISCO,COOPERATIVA MULTIACTIVA DE LA AVIACION CIVIL COLOMBIANA,COOPERATIVA DE EMPLEADOS DE DOW COLOMBIA,COOPERATIVA AVP,FEBOR ENTIDAD COOPERATIVA,...,COOPERATIVA DE AHORRO Y CREDITO DE DROGUISTAS DETALLISTAS,COOPERATIVA DE AHORRO Y CREDITO COLANTA,MICROEMPRESAS DE COLOMBIA COOPERATIVA DE AHORRO Y CREDITO,COOPERATIVA DE AHORRO Y CREDITO CAJA UNION COOPERATIVA,COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO AFROAMERICANA,COPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO CANAPRO,LA COOPERATIVA DE AHORRO Y CREDITO SUCREDITO,COOPERTAIVA ESPECIALIZADA DE AHORRO Y CREDITO TAX LA FERIA,COOPERATIVA SUYA,fecha
0,100000,ACTIVO,1.453604e+11,3.387150e+11,9.879448e+10,1.064674e+10,7.021719e+10,3.751248e+10,1.365023e+10,1.725947e+11,...,2.597647e+11,3.174706e+11,1.964690e+11,1.019668e+10,7.498950e+09,8.204825e+10,7.673873e+10,3.689148e+10,6.785967e+10,2022-02-01
1,110000,EFECTIVO Y EQUIVALENTE AL EFECTIVO,1.094558e+10,1.566943e+10,1.918907e+09,1.552585e+09,4.685907e+09,1.926925e+09,2.472604e+09,9.458176e+09,...,3.586048e+10,2.764945e+10,1.904275e+10,9.197822e+08,5.507006e+08,9.982434e+09,2.782317e+09,5.564935e+09,1.106163e+10,2022-02-01
2,110500,CAJA,2.868046e+08,8.229352e+08,3.589941e+08,1.718631e+08,1.241549e+08,8.000000e+05,6.956260e+08,3.535752e+08,...,2.000000e+06,5.735745e+09,2.193096e+09,6.007630e+07,4.744467e+08,4.490329e+08,2.018711e+08,1.615997e+08,1.612913e+09,2022-02-01
3,110505,CAJA GENERAL,2.791246e+08,8.180852e+08,3.589941e+08,1.718631e+08,1.146549e+08,0.000000e+00,6.956260e+08,3.535752e+08,...,0.000000e+00,5.732195e+09,2.182646e+09,5.907630e+07,4.738467e+08,4.450329e+08,1.998711e+08,1.600997e+08,1.612913e+09,2022-02-01
4,110510,CAJA MENOR,7.680000e+06,4.850000e+06,0.000000e+00,0.000000e+00,9.500000e+06,8.000000e+05,0.000000e+00,0.000000e+00,...,2.000000e+06,3.550000e+06,1.045000e+07,1.000000e+06,6.000000e+05,4.000000e+06,2.000000e+06,1.500000e+06,0.000000e+00,2022-02-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
135686,931500,BIENES Y VALORES RECIBIDOS EN ADMINISTRACIÓN,0.000000e+00,2.470562e+10,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.500000e+10,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2022-05-01
135687,931505,CARTERA FOGACOOP,0.000000e+00,2.470562e+10,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.500000e+10,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2022-05-01
135688,960000,ACREEDORAS POR CONTRA (DB),7.498403e+09,4.308271e+11,1.432583e+11,6.690272e+09,6.667182e+10,2.998245e+10,2.233613e+10,3.804320e+10,...,4.587332e+11,3.204788e+11,1.410674e+11,1.611099e+10,6.967973e+09,1.638770e+10,7.480500e+08,0.000000e+00,1.997420e+10,2022-05-01
135689,960500,RESPONSABILIDADES CONTINGENTES POR EL CONTRARIO,7.498403e+09,4.308271e+11,1.432583e+11,6.690272e+09,6.667182e+10,2.998245e+10,2.233613e+10,3.804320e+10,...,4.587332e+11,3.204788e+11,1.410674e+11,1.611099e+10,6.967973e+09,1.638770e+10,7.480500e+08,0.000000e+00,1.997420e+10,2022-05-01
135690,980000,ACREEDORAS DE CONTROL POR CONTRA (CR),2.103902e+09,2.470562e+10,0.000000e+00,0.000000e+00,1.500000e+10,3.200000e+09,0.000000e+00,1.500000e+10,...,0.000000e+00,0.000000e+00,8.902908e+06,0.000000e+00,0.000000e+00,1.000000e+10,0.000000e+00,0.000000e+00,5.098642e+09,2022-05-01

Generate new columns for the DataFrame

In [9]:
keys = list(coops.columns)
keys.remove("CUENTA")
keys.remove('NOMBRE CUENTA')
keys.remove('fecha')
print(keys)

['COOPERATIVA DE EMPLEADOS DE CAFAM', 'COOPERATIVA DE LOS PROFESIONALES DE LA SALUD COASMEDAS', 'COOPERATIVA PARA EL BIENESTAR SOCIAL', 'COOPERATIVA FINANCIERA SAN FRANCISCO', 'COOPERATIVA MULTIACTIVA DE LA AVIACION CIVIL COLOMBIANA', 'COOPERATIVA DE EMPLEADOS DE DOW COLOMBIA', 'COOPERATIVA AVP', 'FEBOR ENTIDAD COOPERATIVA', 'COOPERATIVA DE PROFESORES DE LA U NACIONAL DE COLOMBIA', 'CAJA COOPERATIVA CREDICOOP', 'COOPERATIVA DE AHORRO Y CREDITO DE SURAMERICA', 'FINANCIERA COOPERATIVA COLOMBIANA DE INGENIEROS', 'COOPERATIVA DE AHORRO Y CREDITO DE TRABAJADORES DE PELDAR Y OTROS DE COLOMBIA', 'COOPERATIVA ALIANZA', 'COOPERATIVA DEL MAGISTERIO', 'COOPERATIVA DE AHORRO Y CREDITO CREDIFLORES', 'COOPERATIVA DE AHORRO Y CREDITO UNIVERSIDAD SANTO TOMAS', 'CAJA COOPERATIVA PETROLERA', 'COOPERATIVA TEXAS LTDA', 'COOPERATIVA DE LOS TRABAJADORES DEL INSTITUTO DE LOS SEGUROS SOCIALES', 'COOPERATIVA DE TRABAJADORES DE BAVARIA DIRECCION Y VENTAS LTDA', 'COPROCENVA COOPERATIVA DE AHORRO Y CREDITO', 'COOPERATIVA DE AHORRO Y CREDITO DE TENJO', 'COOPERATIVA DE TRABAJADORES Y PENSIONADOS DE LA E.A.A.B.', 'COOPERATIVA MULTIACTIVA ANTONIO JOSE JARAMILLO TOBON', 'COOPERATIVA DE TT DE EL COLOMBIANO LTDA.', 'COOPERATIVA NACIONAL DE TRABAJADORES', 'COOPERATIVA LEON XIII DE MACEO LTDA', 'COOPERATIVA SAN PIO X DE GRANADA LTDA', 'COOPERATIVA LEON XIII LTDA DE GUATAPE', 'COOPERATIVA DE AHORRO Y CREDITO RIACHON LTDA.', 'COOPERATIVA SAN ROQUE', 'COOPERATIVA DE TRABAJADORES DE LAS EMPRESAS DEPARTAMENTALES DE ANTIOQU', 'COOPERATIVA DE AHORRO Y CREDITO CREAFAM', 'COOPERATIVA DE TRABAJADORES DEL SENA', 'COOPERATIVA MEDICA DE ANTIOQUIA LTDA', 'COOPERATIVA DE AHORRO Y CREDITO JUAN DE DIOS GOMEZ', 'COOPERATIVA DE TRABAJADORES DEPARTAMENTALES DE ANTIOQUIA', 'COOPERATIVA TELEPOSTAL LTDA', 'COOPERATIVA DE PROFESORES DE LA UNIVERSIDAD DE ANTIOQUIA', 'COOPERATIVA MULTIACTIVA DE EL PAUJIL CAQUETA LIMITADA', 'COOPERATIVA DE AHORRO Y CREDITO COOYAMOR', 'COOPERATIVA DE AHORRO Y CREDITO DE EMPLEADOS DEL SECTOR FINANCIERO', 'AVANCOP COOPERATIVA DE AHORRO Y CREDITO', 'COOCERVUNION COOPERATIVA DE AHORRO Y CREDITO', 'COOPERATIVA DE YARUMAL', 'COOPERATIVA DE AHORRO Y CREDITO PIO XII', 'COOPERATIVA DE EMPLEADOS SURAMERICANA', 'COOPERATIVA DE AHORRO Y CREDITO DEL INEM DE PEREIRA', 'COOPERATIVA DE AHORRO Y CREDITO DE PROFESORES', 'COOPERATIVA SAN VICENTE DE PAUL LTDA.', 'COOPERATIVA AHORRO Y CREDITO GOMEZ PLATA LTDA.', 'COOPERATIVA DE AHORRO Y CREDITO CREAR LTDA CREARCOP', 'FORJAR COOPERATIVA DE AHORRO Y CREDITO', 'COOPERATIVA DE AHORRO Y CREDITO UNIVERSITARIA BOLIVARIANA', 'COOPERATIVA FRATERNIDAD SACERDOTAL LTDA', 'COOPERATIVA MULTIACTIVA EL BAGRE LTDA', 'COOPERATIVA DE AHORRO Y CREDITO SAN LUIS', 'COOPERATIVA DE MUJERES PARA LA PROMOCION INTEGRAL', 'COOPERATIVA INTEGRAL AGROPECUARIA LA PAZ LTDA', 'COOPERATIVA DE AHORRO Y CREDITO CONGENTE', 'COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO DE LA ORINOQUIA', 'COOPERATIVA DE AHORRO Y CREDITO DE TRABAJADORES UNIDOS POR EL PROGRESO', 'GRAN COOPERATIVA DE ENERGIA ELECTRICA Y RECURSOS NATURALES', 'COOPERATIVA DE FOMENTO E INVERSION SOCIAL POPULAR', 'COOPERATIVA ENERGETICA DE AHORRO Y CREDITO', 'COOPERATIVA MULTIACTIVA CON SECCION DE AHORRO Y CREDITO DEL CENTRO COMERCIAL SANANDRESITO LA ISLA LTDA', 'COOPERATIVA DE EMPLEADOS DEL SECTOR COOPERATIVO LTDA.', 'COOPERATIVA MULTIACTIVA DE PROFESIONALES DE SANTANDER LTDA', 'COOPERATIVA MULTIACTIVA DE EMPLEADOS DE COLGATE PALMOLIVE', 'COOPERATIVA DE AHORRO Y CREDITO COOTRAIPI', 'EMPRESA COOPERATIVA DE AHORRO Y CREDITO SIGLO XX LTDA.', 'MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA', 'COOPERATIVA DE LA UNIVERSIDAD NACIONAL DE COLOMBIA', 'COOPERATIVA DE AHORRO Y CREDITO DE TRABAJADORES DE GOODYEAR DE COLOMBIA', 'COOPERATIVA MULTIEMPRESAS', 'CASA NACIONAL DEL PROFESOR', 'COOPERATIVA MULTIACTIVA DE EDUCADORES DE CASANARE LTDA', 'COPERATIVA MULTIACTIVA DE EDUCADORES DE BOYACA', 'COOPERATIVA DE LA GUAJIRA', 'COOPERATIVA DE COMERCIANTES COMERCIACOOP', 'COOPERATIVA MULTIACTIVA DEL INEM DE IBAGUE', 'COOPERATIVA DE MAESTROS Y EMPLEADOS DE LA EDUCACION DEL TOLIMA', 'COOPERATIVA SAN SIMON', 'COOPERATIVA JUDICIAL DEL TOLIMA', 'COOPERATIVA TOLIMENSE DE AHORRO Y CREDITO COOFINANCIAR', 'COOPERATIVA MULTIACTIVA DE LOS TRABAJADORES DEL ISS', 'CESCA COOPERATIVA DE AHORRO Y CREDITO', 'COOPERATIVA MULTIACTIVA DE TRABAJADORES DE LA CHEC LTDA.', 'COOPERATIVA DE PROFESIONALES DE CALDAS', 'COOPERATIVA CALDENSE DEL PROFESOR', 'COOPERATIVA DE PROMOCION SOCIAL', 'COOPERATIVA DE AHORRO Y CREDITO SAN MIGUEL', 'COOPERATIVA LATINOAMERICANA DE AHORRO Y CREDITO', 'COOPERATIVA DE AHORRO Y CREDITO DEL FUTURO', 'COOPERATIVA FUTURISTA DE AHORRO Y CREDITO DE NEIVA', 'COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO COOTRACERREJON', 'COOPERATIVA MULTIACTIVA COOMONOMEROS', 'COOPERATIVA FINANCIERA CAFETERA', 'COOPERATIVA NACIONAL DE AHORRO Y CREDITO AVANZA', 'COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO COOPIGON', 'COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO GUADALUPE', 'COOPERATIVA MULTISERVICIOS BARICHARA LTDA', 'COPERATIVA DE AHORRO Y CREDITO LA BELLEZA', 'COOPERATIVA DE AHORRO Y CREDITO PARA EL DESARROLLO SOLIDARIO DE COLOMBIA', 'COOPERATIVA DE AHORRO Y CREDITO DE LOS TRABAJADORES DEL SECTOR EDUCATIVO DE COLOMBIA LTDA', 'COOPERATIVA INTEGRAL PARA EL DESARROLLO SOCIAL Y ECONOMICO DE TEORAMA', 'COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO COINPROGUA LTDA', 'COOPERATIVA DE AHORRO Y CREDITO DE TELECOMUNICACIONES DE CUCUTA LTDA.', 'COOPERATIVA DE AHORRO Y CREDITO LA PLAYA DE BELEN LTDA', 'COOPERATIVA DE AHORRO Y CREDITO NACIONAL LIMITADA', 'COOPERATIVA DE LOS TRABAJADORES DE LA EDUCACION Y EMPRESARIOS DEL PUTUMAYO', 'COOPERATIVA DE SERVICIOS MULTIPLES MOGOTES', 'COOPERATIVA DE AHORRO Y CREDITO VALLE DE SAN JOSE LTDA', 'COOPERATIVA DE AHORRO Y CREDITO DEL NUCLEO FAMILIAR DE LOS TRAB.DE ECP.LTDA', 'COOPERATIVA DE AHORRO Y CREDITO LA GRANJA LTDA.', 'COOPERATIVA DE AHORRO Y CREDITO TABACALERA Y AGROPECUARIA LTDA', 'COOPERATIVA MULTIACTIVA DEL GUAINIA', 'COOPERATIVA NACIONAL EDUCATIVA DE AHORRO Y CREDITO', 'COOPERATIVA DE TRABAJADORES DE LA EDUCACION DEL RISARALDA', 'COOPERATIVA FAVI UTP', 'COOPERATIVA DE AHORRO Y CREDITO SOCIAL LTDA PROSPERANDO', 'COOPERATIVA DE AHORRO Y CREDITO FINANCIERA COAGROSUR', 'COOPANTEX COOPERATIVA DE AHORRO Y CREDITO', 'COOPERATIVA DE AHORRO Y CREDITO BERLIN', 'COOPERATIVA DE AHORRO Y CREDITO DE AIPE', 'COOPERATIVA DE AHORRO Y CREDITO DE SANTANDER LIMITADA', 'COOPERATIVA BELEN AHORRO Y CREDITO', 'COOPERATIVA DE AHORRO Y CREDITO UNIMOS', 'COOPERATIVA DE AHORRO Y CREDITO FINANCIAFONDOS', 'COOPERATIVA DE AHORRO Y CREDITO UNION COLOMBIANA', 'COOPERATIVA DE AHORRO Y CREDITO DE DROGUISTAS DETALLISTAS', 'COOPERATIVA DE AHORRO Y CREDITO COLANTA', 'MICROEMPRESAS DE COLOMBIA COOPERATIVA DE AHORRO Y CREDITO', 'COOPERATIVA DE AHORRO Y CREDITO CAJA UNION COOPERATIVA', 'COOPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO AFROAMERICANA', 'COPERATIVA ESPECIALIZADA DE AHORRO Y CREDITO CANAPRO', 'LA COOPERATIVA DE AHORRO Y CREDITO SUCREDITO', 'COOPERTAIVA ESPECIALIZADA DE AHORRO Y CREDITO TAX LA FERIA', 'COOPERATIVA SUYA']

In [10]:
indexes_camel = ['Quebranto Patrimonial', 'Relación Solvencia', 'Relación entre Aportes sociales mínimos no reducibles y Capital Social', 'Relación entre el Capital Institucional y el Activo Total', 
                 'Indicador de calidad por riesgo', 'Indicador de calidad por riesgo con castigos', 'Indicador de Cobertura de la Cartera Total en Riesgo', 'Activo Productivo', 'Indicador de Cobertura individual de la cartera improductiva para la cartera en Riesgo',
                 'Indicador de Margen Financiero de Operación', 'Indicador de Margen Operacional', 'Indicador de relación entre las obligaciones financieras y el pasivo total', 'Estructura de Balance',
                 'Indicador de rentabilidad sobre recursos propios - ROE', 'Indicador de margen neto', 'Indicador de rentabilidad sobre el capital invertido - ROIC',
                 'Indicador de Riesgo de Liquidez - IRL']
years = range(2021, 2026)
months = range(1, 13)

We need to parallelize the next cells, because there is a lot of calculations there (for the big dataset)

### Capital

In [11]:
from concurrent.futures import ThreadPoolExecutor
from functools import partial

In [17]:
def calculate_values_capital(company, coops, years, months, indices_camel):
    rows = []
    for y in years:
        for m in months:
            c1 = loss_of_assets(coops, company, y, m)
            c2 = solvency_ratio()
            c3 = min_social_contrib_social_capital(coops, company, y, m)
            c4 = capital_contribution_ratio(coops, company, y, m)

            rows.append([y, m, indices_camel[0], company, c1])
            rows.append([y, m, indices_camel[1], company, c2])
            rows.append([y, m, indices_camel[2], company, c3])
            rows.append([y, m, indices_camel[3], company, c4])
    return rows

# parameters
partial_func_c = partial(calculate_values_capital, coops=coops, years=years, months=months, indices_camel=indexes_camel)

# execute for every company
with ThreadPoolExecutor() as executor:
    resultados = list(executor.map(partial_func_c, keys))

# organize all the info in a dataframe
rows_c = [fila for sublista in resultados for fila in sublista]

df = pd.DataFrame(rows_c, columns=['Año', 'Mes', 'índice CAMEL', 'Cooperativa', 'valor CAMEL'])
df_pivot = df.pivot_table(index=['Año', 'Mes', 'índice CAMEL'], columns='Cooperativa', values='valor CAMEL').reset_index()
df_pivot.columns.name = None

### Assets

In [28]:
def calculate_values_assets_1(company, coops, years, months, indices_camel):
    rows = []
    for y in years:
        for m in months:
            a1 = risk_quality_indicator(coops, company, y, m)
            a2 = risk_quality_with_writeoffs(coops, company, y, m)
            a3 = total_risk_coverage_indicator(coops, company, y, m)

            rows.append([y, m, indices_camel[4], company, a1])
            rows.append([y, m, indices_camel[5], company, a2])
            rows.append([y, m, indices_camel[6], company, a3])
    return rows


def calculate_values_assets_2(company, coops, years, months, indices_camel):
    rows = []
    for y in years:
        for m in months:
            # values for A: ASSETS
            a4 = productive_assets_ratio(coops, company, y, m)
            a5 = individual_coverage_nonproductive_portfolio(coops, company, y, m)

            rows.append([y, m, indices_camel[7], company, a4])
            rows.append([y, m, indices_camel[8], company, a5])
    return rows

first part

In [29]:
partial_func_a = partial(calculate_values_assets_1, coops=coops, years=years, months=months, indices_camel=indexes_camel)

# every company
with ThreadPoolExecutor() as executor:
    resultados = list(executor.map(partial_func_a, keys))

rows_a = [fila for sublista in resultados for fila in sublista]

# Filtra filas donde el valor CAMEL no es nulo/NaN y el año es 2025
rows_a_filtrados = [fila for fila in rows_a if fila[0] == 2025 and pd.notnull(fila[4]) and fila[4] != 0]

# incluir todos los años pero omitir cooperativas sin valores en 2025:
# Primero identifica las cooperativas válidas
coops_con_valores_2025 = set(fila[3] for fila in rows_a if fila[0] == 2025 and pd.notnull(fila[4]) and fila[4] != 0)
rows_a_filtrados = [fila for fila in rows_a if fila[3] in coops_con_valores_2025]

df_a = pd.DataFrame(rows_a_filtrados, columns=['Año', 'Mes', 'índice CAMEL', 'Cooperativa', 'valor CAMEL'])
df_pivot_a = df_a.pivot_table(index=['Año', 'Mes', 'índice CAMEL'], columns='Cooperativa', values='valor CAMEL').reset_index()
df_pivot_a.columns.name = None

In [30]:
df_pivot_a

,Año,Mes,índice CAMEL,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,CAJA COOPERATIVA CREDICOOP,CAJA COOPERATIVA PETROLERA,CASA NACIONAL DEL PROFESOR,CESCA COOPERATIVA DE AHORRO Y CREDITO,COOCERVUNION COOPERATIVA DE AHORRO Y CREDITO,COOPANTEX COOPERATIVA DE AHORRO Y CREDITO,...,COPERATIVA MULTIACTIVA DE EDUCADORES DE BOYACA,COPROCENVA COOPERATIVA DE AHORRO Y CREDITO,EMPRESA COOPERATIVA DE AHORRO Y CREDITO SIGLO XX LTDA.,FEBOR ENTIDAD COOPERATIVA,FINANCIERA COOPERATIVA COLOMBIANA DE INGENIEROS,FORJAR COOPERATIVA DE AHORRO Y CREDITO,GRAN COOPERATIVA DE ENERGIA ELECTRICA Y RECURSOS NATURALES,LA COOPERATIVA DE AHORRO Y CREDITO SUCREDITO,MICROEMPRESAS DE COLOMBIA COOPERATIVA DE AHORRO Y CREDITO,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA"
0,2021,1,Indicador de Cobertura de la Cartera Total en ...,0.055566,0.053379,0.115744,0.022701,0.049609,0.010610,0.087994,...,0.019292,0.026337,0.034718,0.031671,0.063798,0.055208,0.068745,0.015832,0.034574,0.030314
1,2021,1,Indicador de calidad por riesgo,0.029344,0.086836,0.124619,0.018043,0.063940,0.014136,0.103050,...,0.019040,0.029836,0.057121,0.071968,0.047502,0.060850,0.041153,0.015511,0.061412,0.030185
2,2021,1,Indicador de calidad por riesgo con castigos,0.019615,0.095331,0.075134,0.003303,0.033969,0.018697,0.039720,...,0.000516,0.012715,0.073079,0.007629,0.231033,0.035990,0.007803,0.011921,0.141528,0.004795
3,2021,2,Indicador de Cobertura de la Cartera Total en ...,0.065230,0.038193,0.089557,0.020699,0.046888,0.017331,0.085480,...,0.025193,0.028450,0.039215,0.040037,0.070771,0.035189,0.066121,0.017910,0.052338,0.032886
4,2021,2,Indicador de calidad por riesgo,0.040190,0.075898,0.089526,0.016155,0.045786,0.150525,0.119530,...,0.046458,0.031505,0.056031,0.080705,0.026147,0.066102,0.051620,0.037568,0.073247,0.048107
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
175,2025,11,Indicador de calidad por riesgo,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
176,2025,11,Indicador de calidad por riesgo con castigos,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
177,2025,12,Indicador de Cobertura de la Cartera Total en ...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
178,2025,12,Indicador de calidad por riesgo,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
179,2025,12,Indicador de calidad por riesgo con castigos,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

second part

In [31]:
partial_func_a_2 = partial(calculate_values_assets_2, coops=coops, years=years, months=months, indices_camel=indexes_camel)

# every company
with ThreadPoolExecutor() as executor:
    resultados_2 = list(executor.map(partial_func_a_2, keys))

rows_a_2 = [fila for sublista in resultados_2 for fila in sublista]

# incluir todos los años pero omitir cooperativas sin valores en 2025:
# Primero identifica las cooperativas válidas
coops_con_valores_2025_2 = set(fila[3] for fila in rows_a_2 if fila[0] == 2025 and pd.notnull(fila[4]) and fila[4] != 0)
rows_a_filtrados_2 = [fila for fila in rows_a_2 if fila[3] in coops_con_valores_2025_2]

df_a_2 = pd.DataFrame(rows_a_filtrados_2, columns=['Año', 'Mes', 'índice CAMEL', 'Cooperativa', 'valor CAMEL'])
df_pivot_a_2 = df_a_2.pivot_table(index=['Año', 'Mes', 'índice CAMEL'], columns='Cooperativa', values='valor CAMEL').reset_index()
df_pivot_a_2.columns.name = None

In [32]:
df_pivot_a_2

,Año,Mes,índice CAMEL,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,CAJA COOPERATIVA CREDICOOP,CAJA COOPERATIVA PETROLERA,CASA NACIONAL DEL PROFESOR,CESCA COOPERATIVA DE AHORRO Y CREDITO,COOCERVUNION COOPERATIVA DE AHORRO Y CREDITO,COOPANTEX COOPERATIVA DE AHORRO Y CREDITO,...,COPERATIVA MULTIACTIVA DE EDUCADORES DE BOYACA,COPROCENVA COOPERATIVA DE AHORRO Y CREDITO,EMPRESA COOPERATIVA DE AHORRO Y CREDITO SIGLO XX LTDA.,FEBOR ENTIDAD COOPERATIVA,FINANCIERA COOPERATIVA COLOMBIANA DE INGENIEROS,FORJAR COOPERATIVA DE AHORRO Y CREDITO,GRAN COOPERATIVA DE ENERGIA ELECTRICA Y RECURSOS NATURALES,LA COOPERATIVA DE AHORRO Y CREDITO SUCREDITO,MICROEMPRESAS DE COLOMBIA COOPERATIVA DE AHORRO Y CREDITO,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA"
0,2021,1,Activo Productivo,0.849683,0.836182,0.847524,0.787342,0.758971,0.813569,0.862547,...,0.839576,0.927624,0.793425,0.874941,0.597944,0.767561,0.946596,0.901930,0.803447,0.848908
1,2021,1,Indicador de Cobertura individual de la carter...,0.368052,0.637977,0.820234,0.914385,0.787072,0.217691,0.888338,...,0.584411,0.723133,0.706156,0.419189,0.181554,0.761799,0.532663,0.206664,0.613325,0.852915
2,2021,2,Activo Productivo,0.891693,0.856016,0.868504,0.806438,0.746393,0.789267,0.893226,...,0.873551,0.949672,0.796180,0.900145,0.664628,0.734324,0.957687,0.923268,0.885845,0.806865
3,2021,2,Indicador de Cobertura individual de la carter...,0.630189,0.443646,0.823900,0.852717,0.807198,0.137426,0.850376,...,0.457286,0.702165,0.699594,0.471055,0.436296,0.179965,0.413926,0.222500,0.666058,0.487356
4,2021,3,Activo Productivo,0.845382,0.843916,0.852847,0.794876,0.762370,0.810318,0.870493,...,0.844909,0.926671,0.798224,0.886912,0.565216,0.760659,0.950504,0.898259,0.793209,0.847713
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,2025,10,Indicador de Cobertura individual de la carter...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
116,2025,11,Activo Productivo,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
117,2025,11,Indicador de Cobertura individual de la carter...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
118,2025,12,Activo Productivo,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
119,2025,12,Indicador de Cobertura individual de la carter...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

### Managerial

In [33]:
def calculate_values_managerial(company, coops, years, months, indices_camel):
    rows = []
    for y in years:
        for m in months:
            # values for M: MANAGERIAL
            m1 = financial_margin_operation(coops, company, y, m)
            m2 = operational_margin(coops, company, y, m)
            m3 = financial_obligations_ratio(coops, company, y, m)
            m4 = balance_structure(coops, company, y, m)

            rows.append([y, m, indices_camel[9], company, m1])
            rows.append([y, m, indices_camel[10], company, m2])
            rows.append([y, m, indices_camel[11], company, m3])
            rows.append([y, m, indices_camel[12], company, m4])
    return rows

In [34]:
partial_func_m = partial(calculate_values_managerial, coops=coops, years=years, months=months, indices_camel=indexes_camel)

# every company
with ThreadPoolExecutor() as executor:
    resultados = list(executor.map(partial_func_m, keys))

rows_m = [fila for sublista in resultados for fila in sublista]

df_m = pd.DataFrame(rows_m, columns=['Año', 'Mes', 'índice CAMEL', 'Cooperativa', 'valor CAMEL'])
df_pivot_m = df_m.pivot_table(index=['Año', 'Mes', 'índice CAMEL'], columns='Cooperativa', values='valor CAMEL').reset_index()
df_pivot_m.columns.name = None

In [35]:
df_pivot_m

,Año,Mes,índice CAMEL,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,CAJA COOPERATIVA CREDICOOP,CAJA COOPERATIVA PETROLERA,CASA NACIONAL DEL PROFESOR,CESCA COOPERATIVA DE AHORRO Y CREDITO,COOCERVUNION COOPERATIVA DE AHORRO Y CREDITO,COOPANTEX COOPERATIVA DE AHORRO Y CREDITO,...,COPERATIVA MULTIACTIVA DE EDUCADORES DE BOYACA,COPROCENVA COOPERATIVA DE AHORRO Y CREDITO,EMPRESA COOPERATIVA DE AHORRO Y CREDITO SIGLO XX LTDA.,FEBOR ENTIDAD COOPERATIVA,FINANCIERA COOPERATIVA COLOMBIANA DE INGENIEROS,FORJAR COOPERATIVA DE AHORRO Y CREDITO,GRAN COOPERATIVA DE ENERGIA ELECTRICA Y RECURSOS NATURALES,LA COOPERATIVA DE AHORRO Y CREDITO SUCREDITO,MICROEMPRESAS DE COLOMBIA COOPERATIVA DE AHORRO Y CREDITO,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA"
0,2021,1,Estructura de Balance,1.738541,1.687269,1.515012,1.187705,1.964584,1.369032,1.338180,...,1.228318,1.335712,1.808357,1.287252,1.364070,1.475662,2.775355,2.644433,1.878060,1.863718
1,2021,1,Indicador de Margen Financiero de Operación,0.835447,0.801455,0.709589,0.703449,0.833326,0.637803,0.651795,...,0.652784,0.747763,0.867811,0.642544,0.718867,0.860370,0.876935,0.911610,0.885306,0.866134
2,2021,1,Indicador de Margen Operacional,0.281662,-0.001508,-0.044339,0.292152,0.219683,0.098861,0.147045,...,0.230574,0.127692,0.136075,0.192058,-0.105607,0.267655,0.281239,0.400028,0.020771,0.167413
3,2021,1,Indicador de relación entre las obligaciones f...,0.000000,0.033832,0.000000,0.060400,0.000000,0.000000,0.000000,...,0.000000,0.018394,0.065830,0.000000,0.000000,0.000000,0.000000,0.297758,0.122385,0.000000
4,2021,2,Estructura de Balance,1.807411,1.820013,1.496788,1.192809,1.889901,1.364444,1.389044,...,1.270608,1.354679,1.777400,1.284604,1.482266,1.321589,2.667183,2.199104,2.206180,1.800508
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
235,2025,11,Indicador de relación entre las obligaciones f...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
236,2025,12,Estructura de Balance,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
237,2025,12,Indicador de Margen Financiero de Operación,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
238,2025,12,Indicador de Margen Operacional,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
239,2025,12,Indicador de relación entre las obligaciones f...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

### Earnings

In [36]:
def calculate_values_earnings(company, coops, years, months, indices_camel):
    rows = []
    for y in years:
        for m in months:
            # values for E: EARNINGS
            e1 = ROE(coops, company, y, m)
            e2 = net_margin_indicator(coops, company, y, m)
            e3 = ROIC(coops, company, y, m)

            rows.append([y, m, indices_camel[13], company, e1])
            rows.append([y, m, indices_camel[14], company, e2])
            rows.append([y, m, indices_camel[15], company, e3])
    return rows

In [38]:
partial_func_e = partial(calculate_values_earnings, coops=coops, years=years, months=months, indices_camel=indexes_camel)

# every company
with ThreadPoolExecutor() as executor:
    resultados = list(executor.map(partial_func_e, keys))

rows_e = [fila for sublista in resultados for fila in sublista]

df_e = pd.DataFrame(rows_e, columns=['Año', 'Mes', 'índice CAMEL', 'Cooperativa', 'valor CAMEL'])
df_pivot_e = df_e.pivot_table(index=['Año', 'Mes', 'índice CAMEL'], columns='Cooperativa', values='valor CAMEL').reset_index()
df_pivot_e.columns.name = None

In [39]:
df_pivot_e

,Año,Mes,índice CAMEL,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,CAJA COOPERATIVA CREDICOOP,CAJA COOPERATIVA PETROLERA,CASA NACIONAL DEL PROFESOR,CESCA COOPERATIVA DE AHORRO Y CREDITO,COOCERVUNION COOPERATIVA DE AHORRO Y CREDITO,COOPANTEX COOPERATIVA DE AHORRO Y CREDITO,...,COPERATIVA MULTIACTIVA DE EDUCADORES DE BOYACA,COPROCENVA COOPERATIVA DE AHORRO Y CREDITO,EMPRESA COOPERATIVA DE AHORRO Y CREDITO SIGLO XX LTDA.,FEBOR ENTIDAD COOPERATIVA,FINANCIERA COOPERATIVA COLOMBIANA DE INGENIEROS,FORJAR COOPERATIVA DE AHORRO Y CREDITO,GRAN COOPERATIVA DE ENERGIA ELECTRICA Y RECURSOS NATURALES,LA COOPERATIVA DE AHORRO Y CREDITO SUCREDITO,MICROEMPRESAS DE COLOMBIA COOPERATIVA DE AHORRO Y CREDITO,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA"
0,2021,1,Indicador de margen neto,0.251205,-0.019653,-0.079921,0.242726,0.212640,0.133493,0.132738,...,0.250731,0.135008,0.118645,0.205857,0.137903,0.299471,0.406515,0.405155,0.043917,0.164710
1,2021,2,Indicador de margen neto,0.141883,0.044622,0.051629,0.047383,0.076787,-0.256753,0.096169,...,0.070200,0.055364,0.074456,0.140927,0.150408,0.312514,0.319443,0.257903,0.275352,0.070679
2,2021,3,Indicador de margen neto,0.244838,0.015718,0.005008,0.078838,0.215565,0.097741,0.163545,...,0.118091,0.150393,0.005710,0.158648,0.178791,0.331536,0.306543,0.311750,0.207625,0.127797
3,2021,4,Indicador de margen neto,0.263801,0.000586,-0.013719,0.066885,0.183911,0.099448,0.182034,...,0.116497,0.139552,0.068146,0.149240,0.213328,0.338229,0.283060,0.301787,0.247468,0.137001
4,2021,5,Indicador de margen neto,0.255216,0.052473,0.028472,0.085381,0.144892,0.096910,0.133410,...,0.070819,0.085680,0.096430,0.139214,0.190226,0.349099,0.312128,0.255291,0.257131,0.102592
5,2021,6,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
6,2021,7,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
7,2021,8,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
8,2021,9,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
9,2021,10,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
10,2021,11,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
11,2021,12,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
12,2022,1,Indicador de margen neto,0.190952,0.046640,-0.158629,0.013963,0.347734,-0.384075,0.198440,...,0.237885,0.070609,-0.119739,0.096189,0.350901,0.304076,0.128384,0.230998,-0.128899,0.170231
13,2022,2,Indicador de margen neto,0.116121,0.020651,0.053924,0.029321,0.086417,-0.736933,0.109102,...,0.087870,0.023228,0.160486,0.197608,0.388992,0.327067,0.423799,0.197677,0.291610,0.162370
14,2022,3,Indicador de margen neto,0.204770,0.013852,-0.009985,0.093998,0.274570,-0.259630,0.195410,...,0.129893,0.062662,-0.023206,0.046647,0.320528,0.302733,0.235418,0.210073,0.142548,0.011944
15,2022,4,Indicador de margen neto,0.193709,-0.039404,-0.000790,0.112454,0.276645,-0.373830,0.183132,...,0.113028,0.097597,0.356545,0.047647,0.266908,0.303569,0.284859,0.212765,0.150237,0.073498
16,2022,5,Indicador de margen neto,0.179365,0.002602,0.097323,0.110985,0.256931,-0.456159,0.162324,...,0.136589,0.082809,0.260960,0.051242,0.296937,0.363372,0.428007,0.210375,0.231143,0.178534
17,2022,6,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
18,2022,7,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
19,2022,8,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
20,2022,9,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
21,2022,10,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
22,2022,11,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
23,2022,12,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
24,2023,1,Indicador de margen neto,0.032528,-0.234857,-0.162720,-0.155677,0.106255,-0.911104,0.122423,...,0.109293,-0.229911,0.027555,0.123341,0.522842,0.272912,0.552648,0.158464,-0.072182,0.378216
25,2023,2,Indicador de margen neto,0.166027,-0.114850,-0.189668,0.011651,0.158632,-0.815356,0.067305,...,0.033019,-0.162198,-0.005568,0.096715,0.478712,0.279280,0.372991,0.124169,0.067439,0.317117
26,2023,3,Indicador de margen neto,0.106979,-0.097965,0.020678,0.006232,0.134369,-0.489384,0.021083,...,-0.039861,-0.025346,0.066369,0.156545,0.443329,0.331682,0.408636,0.184444,0.211678,0.198586
27,2023,4,Indicador de margen neto,0.131232,-0.088501,0.180980,-0.181919,0.155011,-0.691192,0.044517,...,-0.098506,-0.128854,0.153448,0.118498,0.492866,0.302345,0.413789,0.146224,0.159994,0.269530
28,2023,5,Indicador de margen neto,0.129774,-0.116300,0.135696,-0.174762,0.175274,-0.632401,0.022689,...,-0.098784,-0.139399,0.165904,0.128918,0.520997,0.309580,0.422514,0.168695,0.184473,0.238974
29,2023,6,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
30,2023,7,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
31,2023,8,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
32,2023,9,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
33,2023,10,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
34,2023,11,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
35,2023,12,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
36,2024,1,Indicador de margen neto,0.127028,0.007475,0.008781,0.039339,0.297228,-0.252527,0.105619,...,0.059776,0.014039,-0.045491,0.138090,0.305313,0.322154,0.304802,0.160620,0.569108,0.107854
37,2024,2,Indicador de margen neto,0.147919,0.009387,-0.083908,0.048022,0.323877,-0.283728,0.053669,...,-0.027934,0.038189,0.034303,0.073444,0.328251,0.580934,0.332204,0.210827,0.441720,0.158957
38,2024,3,Indicador de margen neto,0.108240,-0.038460,-0.101858,0.041276,0.275490,-0.199515,0.048322,...,-0.162015,0.029145,0.146169,0.076627,0.352019,0.510068,0.329805,0.206490,0.332551,0.185578
39,2024,4,Indicador de margen neto,0.087823,-0.104802,-0.121797,0.067493,0.242203,-0.158036,0.064222,...,-0.148313,0.022667,0.151839,0.078529,0.339002,0.478349,0.344038,0.206326,0.292789,0.185181
40,2024,5,Indicador de margen neto,0.092708,-0.093944,-0.100614,0.079096,0.250598,-0.077457,0.062029,...,-0.099824,0.023720,0.165238,0.070231,0.353822,0.439134,0.357487,0.200469,0.293306,0.198797
41,2024,6,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
42,2024,7,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
43,2024,8,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
44,2024,9,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
45,2024,10,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
46,2024,11,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
47,2024,12,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
48,2025,1,Indicador de margen neto,0.030282,-0.743552,0.123710,0.072011,0.349696,-0.292237,0.055434,...,0.121061,0.103659,0.108073,0.147483,0.188892,0.213420,0.299014,0.224897,0.369530,0.098169
49,2025,2,Indicador de margen neto,0.029303,-0.286041,0.036486,0.123900,0.169952,-0.147139,0.039457,...,0.053391,0.124313,0.026289,0.148254,0.258252,0.277128,0.226934,0.236399,0.312997,0.078658
50,2025,3,Indicador de margen neto,0.033226,-0.307515,0.033318,0.147425,0.195197,-0.166810,-0.397058,...,0.040678,0.123493,0.148637,0.131711,0.305412,0.288130,0.253017,0.238727,0.277504,0.097496
51,2025,4,Indicador de margen neto,0.038199,-0.231257,0.040248,0.162449,0.198856,-0.118881,0.065387,...,0.012552,0.144890,0.168923,0.170218,0.241880,0.300463,0.272303,0.211172,0.285183,0.098141
52,2025,5,Indicador de margen neto,0.007334,-0.120154,0.037132,0.064398,0.217070,0.039674,-0.074951,...,0.028120,0.133217,0.216553,0.149602,0.265313,0.336965,0.249701,0.149118,0.356199,0.105205
53,2025,6,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
54,2025,7,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
55,2025,8,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
56,2025,9,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
57,2025,10,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
58,2025,11,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
59,2025,12,Indicador de margen neto,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

### Liquidicy

In [40]:
def calculate_values_liquidicy(company, coops, years, months, indices_camel):
    rows = []
    for y in years:
        for m in months:
            # values for L: LIQUIDICY
            l1 = liquidity_risk()
            rows.append([y, m, indices_camel[16], company, l1])
    return rows

In [41]:
partial_func_l = partial(calculate_values_liquidicy, coops=coops, years=years, months=months, indices_camel=indexes_camel)

# every company
with ThreadPoolExecutor() as executor:
    resultados = list(executor.map(partial_func_l, keys))

rows_l = [fila for sublista in resultados for fila in sublista]

df_l = pd.DataFrame(rows_l, columns=['Año', 'Mes', 'índice CAMEL', 'Cooperativa', 'valor CAMEL'])
df_pivot_l = df_l.pivot_table(index=['Año', 'Mes', 'índice CAMEL'], columns='Cooperativa', values='valor CAMEL').reset_index()
df_pivot_l.columns.name = None

In [42]:
df_pivot_l

,Año,Mes,índice CAMEL,AVANCOP COOPERATIVA DE AHORRO Y CREDITO,CAJA COOPERATIVA CREDICOOP,CAJA COOPERATIVA PETROLERA,CASA NACIONAL DEL PROFESOR,CESCA COOPERATIVA DE AHORRO Y CREDITO,COOCERVUNION COOPERATIVA DE AHORRO Y CREDITO,COOPANTEX COOPERATIVA DE AHORRO Y CREDITO,...,COPERATIVA MULTIACTIVA DE EDUCADORES DE BOYACA,COPROCENVA COOPERATIVA DE AHORRO Y CREDITO,EMPRESA COOPERATIVA DE AHORRO Y CREDITO SIGLO XX LTDA.,FEBOR ENTIDAD COOPERATIVA,FINANCIERA COOPERATIVA COLOMBIANA DE INGENIEROS,FORJAR COOPERATIVA DE AHORRO Y CREDITO,GRAN COOPERATIVA DE ENERGIA ELECTRICA Y RECURSOS NATURALES,LA COOPERATIVA DE AHORRO Y CREDITO SUCREDITO,MICROEMPRESAS DE COLOMBIA COOPERATIVA DE AHORRO Y CREDITO,"MULTIACTIVA EL ROBLE, ENTIDAD COOPERATIVA"
0,2021,1,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2021,2,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,2021,3,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,2021,4,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,2021,5,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,2021,6,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,2021,7,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,2021,8,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,2021,9,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,2021,10,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,2021,11,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,2021,12,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
12,2022,1,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,2022,2,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,2022,3,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,2022,4,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
16,2022,5,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,2022,6,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,2022,7,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,2022,8,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,2022,9,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,2022,10,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,2022,11,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,2022,12,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,2023,1,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,2023,2,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,2023,3,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,2023,4,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,2023,5,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,2023,6,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,2023,7,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,2023,8,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,2023,9,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,2023,10,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34,2023,11,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35,2023,12,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36,2024,1,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37,2024,2,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38,2024,3,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39,2024,4,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40,2024,5,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41,2024,6,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42,2024,7,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43,2024,8,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44,2024,9,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45,2024,10,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46,2024,11,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47,2024,12,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48,2025,1,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,2025,2,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50,2025,3,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
51,2025,4,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
52,2025,5,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,2025,6,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
54,2025,7,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
55,2025,8,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
56,2025,9,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
57,2025,10,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
58,2025,11,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
59,2025,12,Indicador de Riesgo de Liquidez - IRL,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## CSV for BD

Write on .csv the data from DataFrames:

DataFrames's names and their title:
* 'df_pivot': Capital
* 'df_pivot_a' y 'df_pivot_a_2': Assets
* 'df_pivot_m': Managerial
* 'df_pivot_e': Earnings
* 'df_pivot_l': Liquidicy

In [43]:
df_pivot.to_csv("../tablas/camel/Capital.csv", index=False, encoding="utf-8")
# assets
assets = pd.concat([df_pivot_a, df_pivot_a_2], ignore_index=True)
assets.to_csv("../tablas/camel/Assets.csv", index=False, encoding="utf-8")
# ---
df_pivot_m.to_csv("../tablas/camel/Managerial.csv", index=False, encoding="utf-8")
df_pivot_e.to_csv("../tablas/camel/Earnings.csv", index=False, encoding="utf-8")
df_pivot_l.to_csv("../tablas/camel/Liquidity.csv", index=False, encoding="utf-8")